version: '3'

services:

  app:
    build: .
    tty: true
    container_name: codeflix-catalog-admin-client
    # entrypoint: ./entrypoint.sh
    ports:
      - "5147:5147"
    volumes:
      - ..:/home/node/app